name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Faisal2506

      - name: Commit and push generated files
        uses: EndBug/add-and-commit@v9
        with:
          message: "generate 3d contribution graph"
          add: "profile-3d-contrib/*.svg"
